### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [michaldrabik/muzei-pixelart-android#1]
Hi,

Since this app is LGPL v3 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by michaldrabik** [comment]
Hi @Poussinou, no problem in adding the app into F-Droid. External help could be fine as I have lot on my mind right now. Regards.

**Comment by Poussinou** [comment]
Here you go with the RFP: https://gitlab.com/fdroid/rfp/issues/1222

**Comment by IzzySoft** [comment]
@michaldrabik as @Poussinou didn't transfer the updates here you might have missed them. Currently there's a big show-stopper to F-Droid inclusion: Fabric (and Crashlytics) collide with the inclusion criteria. Could you provide a build flavor coming without that? And maybe even establish [Fastlane file structure](https://gitlab.com/snippets/1895688)?

**Comment by IzzySoft** [comment]
@michaldrabik the RFP on our end is stalled pending your answer. So any chance for a FOSS flavor and for Fastlane structures – or do we have to abandon the approach and close the RFP?
