### ISSUE TITLE
Image saving

### ISSUE THREAD

**Issue by jhwilborn** [michaldrabik/muzei-pixelart-android#2]
Would really love to be able to save images somehow. I peeked at the source just in case but didn't see any way to get at the original files. Any help/info would be greatly appreciated!

**Comment by michaldrabik** [comment]
@JasonHWGit Hello. It's not possible at this moment. I've created #3 and will try to add this feature soon.

**Comment by michaldrabik** [comment]
Done in 1.1.0 - should be live in PlayStore soon
